
package com.mycompany.PuntoDeVenta2;

/**
 *
 * @author VICTECH
 */
public class Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelFondoAmarillo = new javax.swing.JPanel();
        jLabelProductos = new javax.swing.JLabel();
        JPanelFondoGris = new javax.swing.JPanel();
        JPanelFondoGris1 = new javax.swing.JPanel();
        JPanelFondoGris3 = new javax.swing.JPanel();
        JPanelFondoGris2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelFondoAmarillo.setBackground(new java.awt.Color(0, 102, 204));

        jLabelProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductos.setText("CONFIGURACION");

        javax.swing.GroupLayout JPanelFondoAmarilloLayout = new javax.swing.GroupLayout(JPanelFondoAmarillo);
        JPanelFondoAmarillo.setLayout(JPanelFondoAmarilloLayout);
        JPanelFondoAmarilloLayout.setHorizontalGroup(
            JPanelFondoAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFondoAmarilloLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        JPanelFondoAmarilloLayout.setVerticalGroup(
            JPanelFondoAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFondoAmarilloLayout.createSequentialGroup()
                .addComponent(jLabelProductos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelFondoAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        JPanelFondoGris.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPanelFondoGrisLayout = new javax.swing.GroupLayout(JPanelFondoGris);
        JPanelFondoGris.setLayout(JPanelFondoGrisLayout);
        JPanelFondoGrisLayout.setHorizontalGroup(
            JPanelFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        JPanelFondoGrisLayout.setVerticalGroup(
            JPanelFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelFondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 80));

        JPanelFondoGris1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout JPanelFondoGris1Layout = new javax.swing.GroupLayout(JPanelFondoGris1);
        JPanelFondoGris1.setLayout(JPanelFondoGris1Layout);
        JPanelFondoGris1Layout.setHorizontalGroup(
            JPanelFondoGris1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        JPanelFondoGris1Layout.setVerticalGroup(
            JPanelFondoGris1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelFondoGris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1440, -1));

        JPanelFondoGris3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout JPanelFondoGris3Layout = new javax.swing.GroupLayout(JPanelFondoGris3);
        JPanelFondoGris3.setLayout(JPanelFondoGris3Layout);
        JPanelFondoGris3Layout.setHorizontalGroup(
            JPanelFondoGris3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        JPanelFondoGris3Layout.setVerticalGroup(
            JPanelFondoGris3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelFondoGris3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 80));

        JPanelFondoGris2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPanelFondoGris2Layout = new javax.swing.GroupLayout(JPanelFondoGris2);
        JPanelFondoGris2.setLayout(JPanelFondoGris2Layout);
        JPanelFondoGris2Layout.setHorizontalGroup(
            JPanelFondoGris2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        JPanelFondoGris2Layout.setVerticalGroup(
            JPanelFondoGris2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelFondoGris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFondoAmarillo;
    private javax.swing.JPanel JPanelFondoGris;
    private javax.swing.JPanel JPanelFondoGris1;
    private javax.swing.JPanel JPanelFondoGris2;
    private javax.swing.JPanel JPanelFondoGris3;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
