
package com.mycompany.PuntoDeVenta2;

import java.awt.BorderLayout;

/**
 *
 * @author VICTECH
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public JFMenu() { // Constructor de la clase JFMenu
    initComponents(); // Inicializa los componentes del formulario
    
    Venta venta = new Venta(); // Crea una instancia de la clase Ventas
    venta.setSize(1440, 640); // Define tamaño: 1440x640 píxeles
    venta.setLocation(0, 0); // Posiciona en la esquina superior izquierda
    
    PanelFondoVentas.removeAll(); // Elimina componentes del contenedor
    PanelFondoVentas.add(venta, BorderLayout.CENTER); // Agrega "ventas" al centro del contenedor
    PanelFondoVentas.revalidate(); // Actualiza el contenedor
    PanelFondoVentas.repaint(); // Redibuja el contenedor
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        PanelFondo = new javax.swing.JPanel();
        PanelFondoVentas = new javax.swing.JPanel();
        PanelFondoBotones = new javax.swing.JPanel();
        jButtonVentas = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonInventarios = new javax.swing.JButton();
        jButtonConfiguracion = new javax.swing.JButton();
        jButtonLicencia = new javax.swing.JButton();
        PanelFondoCabezado = new javax.swing.JPanel();
        JLabelLogoCabecera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        PanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondoVentas.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout PanelFondoVentasLayout = new javax.swing.GroupLayout(PanelFondoVentas);
        PanelFondoVentas.setLayout(PanelFondoVentasLayout);
        PanelFondoVentasLayout.setHorizontalGroup(
            PanelFondoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        PanelFondoVentasLayout.setVerticalGroup(
            PanelFondoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        PanelFondo.add(PanelFondoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1440, 640));

        jButtonVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVentas.setText("Ventas");
        jButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentasActionPerformed(evt);
            }
        });

        jButtonProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProductos.setText("Productos");
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });

        jButtonInventarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInventarios.setText("Inventarios");
        jButtonInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventariosActionPerformed(evt);
            }
        });

        jButtonConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConfiguracion.setText("Configuracion");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        jButtonLicencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLicencia.setText("Licencia");

        javax.swing.GroupLayout PanelFondoBotonesLayout = new javax.swing.GroupLayout(PanelFondoBotones);
        PanelFondoBotones.setLayout(PanelFondoBotonesLayout);
        PanelFondoBotonesLayout.setHorizontalGroup(
            PanelFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoBotonesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFondoBotonesLayout.setVerticalGroup(
            PanelFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelFondo.add(PanelFondoBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1440, -1));

        PanelFondoCabezado.setBackground(new java.awt.Color(36, 65, 124));

        JLabelLogoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Punto logo.png"))); // NOI18N

        javax.swing.GroupLayout PanelFondoCabezadoLayout = new javax.swing.GroupLayout(PanelFondoCabezado);
        PanelFondoCabezado.setLayout(PanelFondoCabezadoLayout);
        PanelFondoCabezadoLayout.setHorizontalGroup(
            PanelFondoCabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoCabezadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLabelLogoCabecera)
                .addContainerGap(1098, Short.MAX_VALUE))
        );
        PanelFondoCabezadoLayout.setVerticalGroup(
            PanelFondoCabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoCabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelLogoCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelFondo.add(PanelFondoCabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
    Productos productos = new Productos(); // Crea una instancia de la clase Productos
    productos.setSize(1440, 640); // Define tamaño: 1440x640 píxeles
    productos.setLocation(0, 0); // Posiciona en la esquina superior izquierda

    PanelFondoVentas.removeAll(); // Elimina componentes del contenedor
    PanelFondoVentas.add(productos, BorderLayout.CENTER); // Agrega "productos" al centro del contenedor
    PanelFondoVentas.revalidate(); // Actualiza el contenedor
    PanelFondoVentas.repaint(); // Redibuja el contenedor
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
    Venta venta = new Venta(); // Crea una instancia de la clase Ventas
    venta.setSize(1440, 640); // Define tamaño: 1440x640 píxeles
    venta.setLocation(0, 0); // Posiciona en la esquina superior izquierda

    PanelFondoVentas.removeAll(); // Elimina componentes existentes del contenedor
    PanelFondoVentas.add(venta, BorderLayout.CENTER); // Agrega "ventas" al centro del contenedor
    PanelFondoVentas.revalidate(); // Actualiza el contenedor para reflejar los cambios
    PanelFondoVentas.repaint(); // Redibuja el contenedor para mostrar el nuevo contenido
    }//GEN-LAST:event_jButtonVentasActionPerformed

    private void jButtonInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventariosActionPerformed
    Inventarios inventarios = new Inventarios(); // Crea una instancia de la clase Inventarios
    inventarios.setSize(1440, 640); // Define tamaño: 1440x640 píxeles
    inventarios.setLocation(0, 0); // Posiciona en la esquina superior izquierda

    PanelFondoVentas.removeAll(); // Elimina los componentes existentes del contenedor
    PanelFondoVentas.add(inventarios, BorderLayout.CENTER); // Agrega "inventarios" al centro del contenedor
    PanelFondoVentas.revalidate(); // Actualiza el contenedor para reflejar los cambios
    PanelFondoVentas.repaint(); // Redibuja el contenedor para mostrar el nuevo contenido
    }//GEN-LAST:event_jButtonInventariosActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
    Configuracion configuracion = new Configuracion(); // Crea una instancia de la clase Configuracion
    configuracion.setSize(1440, 640); // Define tamaño: 1440x640 píxeles
    configuracion.setLocation(0, 0); // Posiciona en la esquina superior izquierda

    PanelFondoVentas.removeAll(); // Elimina los componentes existentes del contenedor
    PanelFondoVentas.add(configuracion, BorderLayout.CENTER); // Agrega "configuracion" al centro del contenedor
    PanelFondoVentas.revalidate(); // Actualiza el contenedor para reflejar los cambios
    PanelFondoVentas.repaint(); // Redibuja el contenedor para mostrar el nuevo contenido
    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogoCabecera;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelFondoBotones;
    private javax.swing.JPanel PanelFondoCabezado;
    private javax.swing.JPanel PanelFondoVentas;
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JButton jButtonInventarios;
    private javax.swing.JButton jButtonLicencia;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
